spring:
  application:
    name: processing-center
  config:
    import: configserver:http://localhost:8888

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: card-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  level:
    root: INFO
    com:
      netflix:
        eureka: off
        discovery: off