spring:
  application:
    name: processing-center
  config:
    import: configserver:http://localhost:8888

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: card-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5
      retries: 10
    topics:
      card-transfer-to-issuing: card-created-to-issuing-events-topic
      card-transfer-to-processing: card-created-to-processing-events-topic
      key: 1
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
tracing:
  url: http://localhost:4317

logging:
  level:
    root: INFO
    com:
      netflix:
        eureka: off
        discovery: off
    io.opentelemetry: DEBUG
    io.micrometer.tracing: DEBUG
    org:
      springframework:
        boot:
          autoconfigure=DEBUG:
  file:
    name: logs/processing-center.log

---

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/edme-realm
