spring:
  application:
    name: gateway
  config:
    import: configserver:http://localhost:8888

logging:
  level:
    root: INFO
#    org.springframework.beans.factory.support.PostProcessorRegistrationDelegate: error
#    com:
#      netflix:
#        eureka: off
#        discovery: off
  file:
    name: logs/gateway.log