spring:
  application:
    name: issuing-bank
  config:
    import: configserver:http://localhost:8888

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: card-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      card-transfer-to-processing: card-created-to-processing-events-topic
      card-transfer-to-issuing: card-created-to-issuing-events-topic
      key: 1
logging:
  level:
    root: INFO
    com:
      netflix:
        eureka: off
        discovery: off